### ISSUE TITLE
Constraint file for MetaCyc DB

### ISSUE THREAD

**Issue by Vykintasj** [sandialabs/RetSynth#1]
Hello,

I ran into several errors when executing:
`python rs.py -gdb meta_rs.db -mc meta/22.5/data/metabolic-reactions.xml -t test_in.txt
`
Not sure if I am running it correctly, as I could not find examples running specific databases.
First I got the error:
```
Traceback (most recent call last):
  File "rs.py", line 864, in <module>
    main()
  File "rs.py", line 807, in main
    LP = retrieve_constraints(args, all_db_reactions, all_db_compounds, ignore_reactions, include_rxns, database)
  File "rs.py", line 676, in retrieve_constraints
    reverse_constraints=False)
TypeError: __init__() got an unexpected keyword argument 'reverse_constraints'
```
I renamed 'reverse_constraints' to 'reverse_direction' as I could not find the argument 'reverse_constraints' in the function. Afterwards I got the following error:
```
Traceback (most recent call last):
  File "rs.py", line 864, in <module>
    main()
  File "rs.py", line 807, in main
    LP = retrieve_constraints(args, all_db_reactions, all_db_compounds, ignore_reactions, include_rxns, database)
  File "rs.py", line 676, in retrieve_constraints
    reverse_direction=False)
  File "/home/vykintas_jauniskis/git-clones/RetSynth/rs/ShortestPath/constraints.py", line 84, in __init__
    self.variables = self.lp.variables()
AttributeError: 'list' object has no attribute 'variables'
```
I am not sure whether the origin of the error is my previous edit, or if your program requires the constraint file every time. In that case, what constraint file should I use when using MetaCyc database?

My test_input.txt:
```
#name
1-butanol
```
I also get these warnings, however I assume for testing purposes it is not relevant:
```
WARNING: User specified specific database but not constraint file therefore default constraint file will be used but may not match user specified database
WARNING: No compartment info going to default c0
WARNING: No organism was given or found
WARNING: No database constraint file specified using pre constructed database constraint file for database with media Complete
```

Thanks for your help. Best regards,
Vykintas

**Comment by lwhitmore** [comment]
Hi Vykintas, 
You need to specify a constraint file with the parameter "-gdbc new_constraint_file.constraints". 

Try that and let me know how it goes. 

Leanne

**Comment by Vykintasj** [comment]
Hi, the problem remained. I managed to fix it when replacing some of the code in the 'retrieve_constraints' function:
```
    if args.generate_database_constraints:
        LP = co.ConstructInitialLP(allrxns, allcpds, DB,
                                   ignore_reactions, include_rxns,  #True,
                                   reverse_direction=False)
        with open(args.generate_database_constraints, 'wb') as fout1:
            #cPickle.dump(LP.A, fout1)
            #cPickle.dump(LP.allcpds, fout1)
            cPickle.dump(LP, fout1)

    elif args.database_constraints:
        with open(args.database_constraints, 'rb') as fin1:
            #A = cPickle.load(fin1)
            #allcompounds4matrix = cPickle.load(fin1)
#             LP = co.ConstructInitialLP(allrxns, allcompounds4matrix, DB,
#                                        ignore_reactions, include_rxns, A,
#                                        reverse_direction=False)
            LP = cPickle.load(fin1)
        A = LP.A
        allcompounds4matrix = LP.allcpds
```

If I understand correctly, the issue was that two different variables were written onto the same 'fout1' output file:
```
cPickle.dump(LP.A, fout1)
cPickle.dump(LP.allcpds, fout1)
```
Let me know if that will not result in other instabilities, or if you decide to update the version.

Best regards,
Vykintas

**Comment by lwhitmore** [comment]
Vykintas, 
I believe this will cause downstream issues.   I don't know why it wouldn't be able to load and dump two variables in the fout1 and fin1 as this has always worked for me. 

Your command "python rs.py -gdb meta_rs.db -mc meta/22.5/data/metabolic-reactions.xml -t test_in.txt" needs to add the -gdbc command as mentioned previously.  Additionally, I notice in your test_in.txt you don't have a target organism specified is that intentional?  


Can you try with out any of your modifications the following command,  I just noticed another parameter that needs to be specified.
"python rs.py -gdb meta_rs.db -gdbc meta_rs.constraints --metacyc -mc meta/22.5/data/metabolic-reactions.xml -t test_in.txt"
